//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloWeb1Clase13.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteHobbie
    {
        public string codigo { get; set; }
        public string identificacion { get; set; }
        public string codigoHobbie { get; set; }
    
        public virtual estudiente estudiente { get; set; }
        public virtual Hobbie Hobbie { get; set; }
    }
}
